name: otelia.aufderhar
description: global
version: 0.0.1
author: tjechlt6.rpoj32p3@yebubp21.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: oteliaaufderhar
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2025-09-19 23:36:03'
pipelines:
  pipelines/Mr__Pete_HaagAl_B__TrossPenny_Reilly:
    name: Mr__Pete_HaagAl_B__TrossPenny_Reilly
    description: null
    author: tjechlt6.rpoj32p3@yebubp21.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2025-09-19 23:36:03'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-09-19 23:36:03'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-09-19T23:36:03.261015Z'
  name: plibMaven
  version: 8.14.0-SNAPSHOT
  id: '976387749'
  createdAt: '2025-09-19T23:36:03.261015Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
projectConfigurations: {}
